In [1]:
import torch
import torch.nn as nn

from PIL import Image
import time

from mss.linux import MSS as mss
import cv2 as cv
import numpy as np

# Load YOLOv5 with PyTorch Hub from Ultralytics
model = torch.hub.load("ultralytics/yolov5", "custom", path="csgo-detection-v3.pt")

if torch.cuda.is_available():
    model.cuda()

Using cache found in /home/dalai/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2022-6-4 Python-3.10.1 torch-1.11.0+cu102 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4040MiB)

Fusing layers... 
Model summary: 367 layers, 46135203 parameters, 0 gradients
Adding AutoShape... 


In [2]:
img = Image.open("csgo.mp4-out000014.png")


In [3]:
results = model(img)

In [4]:
def get_targets(results: list, cls: list[int]):
    return [target for target in results.xywh[0] if target[5] in cls]

In [5]:
targets = get_targets(results, cls=[2,3])
targets

[tensor([647.32275, 174.81888,  42.87860,  44.33978,   0.90040,   3.00000], device='cuda:0'),
 tensor([201.32089, 181.86473,  75.81676,  62.98956,   0.88568,   3.00000], device='cuda:0'),
 tensor([1.10529e+03, 1.66706e+02, 2.32924e+01, 2.31361e+01, 8.66877e-01, 3.00000e+00], device='cuda:0'),
 tensor([687.98871, 160.46310,  25.15295,  33.20045,   0.83823,   3.00000], device='cuda:0')]

In [6]:
for target in targets:
    print(target)

tensor([647.32275, 174.81888,  42.87860,  44.33978,   0.90040,   3.00000], device='cuda:0')
tensor([201.32089, 181.86473,  75.81676,  62.98956,   0.88568,   3.00000], device='cuda:0')
tensor([1.10529e+03, 1.66706e+02, 2.32924e+01, 2.31361e+01, 8.66877e-01, 3.00000e+00], device='cuda:0')
tensor([687.98871, 160.46310,  25.15295,  33.20045,   0.83823,   3.00000], device='cuda:0')
